export const amberMinimal = {
  label: 'Amber Minimal',
  createdAt: '2025-04-27',
  styles: {
    light: {
      background: '#ffffff',
      foreground: '#262626',
      card: '#ffffff',
      'card-foreground': '#262626',
      popover: '#ffffff',
      'popover-foreground': '#262626',
      primary: '#f59e0b',
      'primary-foreground': '#000000',
      secondary: '#f3f4f6',
      'secondary-foreground': '#4b5563',
      muted: '#f9fafb',
      'muted-foreground': '#6b7280',
      accent: '#fffbeb',
      'accent-foreground': '#92400e',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#e5e7eb',
      input: '#e5e7eb',
      ring: '#f59e0b',
      'chart-1': '#f59e0b',
      'chart-2': '#d97706',
      'chart-3': '#b45309',
      'chart-4': '#92400e',
      'chart-5': '#78350f',
      'background-secondary': '#f9fafb',
      sidebar: '#f9fafb',
      'sidebar-foreground': '#262626',
      'sidebar-primary': '#f59e0b',
      'sidebar-primary-foreground': '#ffffff',
      'sidebar-accent': '#fffbeb',
      'sidebar-accent-foreground': '#92400e',
      'sidebar-border': '#e5e7eb',
      'sidebar-ring': '#f59e0b',
      'font-sans': 'Inter, sans-serif',
      'font-serif': 'Source Serif 4, serif',
      'font-mono': 'JetBrains Mono, monospace',
      radius: '0.375rem',
      'shadow-color': 'hsl(0 0% 0%)',
      'shadow-opacity': '0.1',
      'shadow-blur': '8px',
      'shadow-spread': '-1px',
      'shadow-offset-x': '0px',
      'shadow-offset-y': '4px',
      'letter-spacing': '0em',
      spacing: '0.25rem',
    },
    dark: {
      background: '#171717',
      foreground: '#e5e5e5',
      card: '#262626',
      'card-foreground': '#e5e5e5',
      popover: '#262626',
      'popover-foreground': '#e5e5e5',
      primary: '#f59e0b',
      'primary-foreground': '#000000',
      secondary: '#262626',
      'secondary-foreground': '#e5e5e5',
      muted: '#262626',
      'muted-foreground': '#a3a3a3',
      accent: '#92400e',
      'accent-foreground': '#fde68a',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#404040',
      input: '#404040',
      ring: '#f59e0b',
      'chart-1': '#fbbf24',
      'chart-2': '#d97706',
      'chart-3': '#92400e',
      'chart-4': '#b45309',
      'chart-5': '#92400e',
      'background-secondary': '#0f0f0f',
      sidebar: '#0f0f0f',
      'sidebar-foreground': '#e5e5e5',
      'sidebar-primary': '#f59e0b',
      'sidebar-primary-foreground': '#ffffff',
      'sidebar-accent': '#92400e',
      'sidebar-accent-foreground': '#fde68a',
      'sidebar-border': '#404040',
      'sidebar-ring': '#f59e0b',
    },
  },
};
