export const midnightBloom = {
  label: 'Midnight Bloom',
  styles: {
    light: {
      background: '#f9f9f9',
      foreground: '#333333',
      card: '#ffffff',
      'card-foreground': '#333333',
      popover: '#ffffff',
      'popover-foreground': '#333333',
      primary: '#6c5ce7',
      'primary-foreground': '#ffffff',
      secondary: '#a1c9f2',
      'secondary-foreground': '#333333',
      muted: '#c9c4b5',
      'muted-foreground': '#6e6e6e',
      accent: '#8b9467',
      'accent-foreground': '#ffffff',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#d4d4d4',
      input: '#d4d4d4',
      ring: '#6c5ce7',
      'chart-1': '#6c5ce7',
      'chart-2': '#8e44ad',
      'chart-3': '#4b0082',
      'chart-4': '#6495ed',
      'chart-5': '#4682b4',
      radius: '0.5rem',
      sidebar: '#f9f9f9',
      'sidebar-foreground': '#333333',
      'sidebar-primary': '#6c5ce7',
      'sidebar-primary-foreground': '#ffffff',
      'sidebar-accent': '#8b9467',
      'sidebar-accent-foreground': '#ffffff',
      'sidebar-border': '#d4d4d4',
      'sidebar-ring': '#6c5ce7',
      'font-sans': 'Montserrat, sans-serif',
      'font-serif': 'Playfair Display, serif',
      'font-mono': 'Source Code Pro, monospace',
      'shadow-color': 'hsl(0 0% 0%)',
      'shadow-opacity': '0.1',
      'shadow-blur': '10px',
      'shadow-spread': '-2px',
      'shadow-offset-x': '0px',
      'shadow-offset-y': '5px',
    },
    dark: {
      background: '#1a1d23',
      foreground: '#e5e5e5',
      card: '#2f3436',
      'card-foreground': '#e5e5e5',
      popover: '#2f3436',
      'popover-foreground': '#e5e5e5',
      primary: '#6c5ce7',
      'primary-foreground': '#ffffff',
      secondary: '#4b0082',
      'secondary-foreground': '#e5e5e5',
      muted: '#444444',
      'muted-foreground': '#a3a3a3',
      accent: '#6495ed',
      'accent-foreground': '#e5e5e5',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#444444',
      input: '#444444',
      ring: '#6c5ce7',
      'chart-1': '#6c5ce7',
      'chart-2': '#8e44ad',
      'chart-3': '#4b0082',
      'chart-4': '#6495ed',
      'chart-5': '#4682b4',
      radius: '0.5rem',
      sidebar: '#1a1d23',
      'sidebar-foreground': '#e5e5e5',
      'sidebar-primary': '#6c5ce7',
      'sidebar-primary-foreground': '#ffffff',
      'sidebar-accent': '#6495ed',
      'sidebar-accent-foreground': '#e5e5e5',
      'sidebar-border': '#444444',
      'sidebar-ring': '#6c5ce7',
    },
  },
};
