export const quantumRose = {
  label: 'Quantum Rose',
  createdAt: '2025-04-03',
  styles: {
    light: {
      background: '#fff0f8',
      foreground: '#91185c',
      card: '#fff7fc',
      'card-foreground': '#91185c',
      popover: '#fff7fc',
      'popover-foreground': '#91185c',
      primary: '#e6067a',
      'primary-foreground': '#ffffff',
      secondary: '#ffd6ff',
      'secondary-foreground': '#91185c',
      muted: '#ffe3f2',
      'muted-foreground': '#c04283',
      accent: '#ffc1e3',
      'accent-foreground': '#91185c',
      destructive: '#d13869',
      'destructive-foreground': '#ffffff',
      border: '#ffc7e6',
      input: '#ffd6ff',
      ring: '#e6067a',
      'chart-1': '#e6067a',
      'chart-2': '#c44b97',
      'chart-3': '#9969b6',
      'chart-4': '#7371bf',
      'chart-5': '#5e84ff',
      sidebar: '#ffedf6',
      'sidebar-foreground': '#91185c',
      'sidebar-primary': '#e6067a',
      'sidebar-primary-foreground': '#ffffff',
      'sidebar-accent': '#ffc1e3',
      'sidebar-accent-foreground': '#91185c',
      'sidebar-border': '#ffddf0',
      'sidebar-ring': '#e6067a',
      'font-sans': 'Poppins, sans-serif',
      'font-serif': 'Playfair Display, serif',
      'font-mono': 'Space Mono, monospace',
      radius: '0.5rem',
      'shadow-color': 'hsl(330 70% 30% / 0.12)',
      'shadow-opacity': '0.18',
      'shadow-blur': '0px',
      'shadow-spread': '0px',
      'shadow-offset-x': '0px',
      'shadow-offset-y': '3px',
    },
    dark: {
      background: '#1a0922',
      foreground: '#ffb3ff',
      card: '#2a1435',
      'card-foreground': '#ffb3ff',
      popover: '#2a1435',
      'popover-foreground': '#ffb3ff',
      primary: '#ff6bef',
      'primary-foreground': '#180518',
      secondary: '#46204f',
      'secondary-foreground': '#ffb3ff',
      muted: '#331941',
      'muted-foreground': '#d67ad6',
      accent: '#5a1f5d',
      'accent-foreground': '#ffb3ff',
      destructive: '#ff2876',
      'destructive-foreground': '#f9f9f9',
      border: '#4a1b5f',
      input: '#46204f',
      ring: '#ff6bef',
      'chart-1': '#ff6bef',
      'chart-2': '#c359e3',
      'chart-3': '#9161ff',
      'chart-4': '#6f73e2',
      'chart-5': '#547aff',
      sidebar: '#1c0d25',
      'sidebar-foreground': '#ffb3ff',
      'sidebar-primary': '#ff6bef',
      'sidebar-primary-foreground': '#180518',
      'sidebar-accent': '#5a1f5d',
      'sidebar-accent-foreground': '#ffb3ff',
      'sidebar-border': '#4a1b5f',
      'sidebar-ring': '#ff6bef',
      'font-sans': 'Quicksand, sans-serif',
      'font-serif': 'Playfair Display, serif',
      'font-mono': 'Space Mono, monospace',
      'shadow-color': 'hsl(300 80% 50% / 0.25)',
    },
  },
};
