export const twitter = {
  label: 'Twitter',
  createdAt: '2025-04-24',
  styles: {
    light: {
      background: '#ffffff',
      foreground: '#0f1419',
      card: '#f7f8f8',
      'card-foreground': '#0f1419',
      popover: '#ffffff',
      'popover-foreground': '#0f1419',
      primary: '#1e9df1',
      'primary-foreground': '#ffffff',
      secondary: '#0f1419',
      'secondary-foreground': '#ffffff',
      muted: '#E5E5E6',
      'muted-foreground': '#0f1419',
      accent: '#E3ECF6',
      'accent-foreground': '#1e9df1',
      destructive: '#f4212e',
      'destructive-foreground': '#ffffff',
      border: '#e1eaef',
      input: '#f7f9fa',
      ring: '#1da1f2',
      'chart-1': '#1e9df1',
      'chart-2': '#00b87a',
      'chart-3': '#f7b928',
      'chart-4': '#17bf63',
      'chart-5': '#e0245e',
      'background-secondary': '#f7f8f8',
      sidebar: '#f7f8f8',
      'sidebar-foreground': '#0f1419',
      'sidebar-primary': '#1e9df1',
      'sidebar-primary-foreground': '#ffffff',
      'sidebar-accent': '#E3ECF6',
      'sidebar-accent-foreground': '#1e9df1',
      'sidebar-border': '#e1e8ed',
      'sidebar-ring': '#1da1f2',
      'font-sans': 'Open Sans, sans-serif',
      'font-serif': 'Georgia, serif',
      'font-mono': 'Menlo, monospace',
      radius: '1.3rem',
      'shadow-color': 'rgba(29,161,242,0.15)',
      'shadow-opacity': '0',
      'shadow-blur': '0px',
      'shadow-spread': '0px',
      'shadow-offset-x': '0px',
      'shadow-offset-y': '2px',
    },
    dark: {
      background: '#000000',
      foreground: '#e7e9ea',
      card: '#17181c',
      'card-foreground': '#d9d9d9',
      popover: '#000000',
      'popover-foreground': '#e7e9ea',
      primary: '#1c9cf0',
      'primary-foreground': '#ffffff',
      secondary: '#f0f3f4',
      'secondary-foreground': '#0f1419',
      muted: '#181818',
      'muted-foreground': '#72767a',
      accent: '#061622',
      'accent-foreground': '#1c9cf0',
      destructive: '#f4212e',
      'destructive-foreground': '#ffffff',
      border: '#242628',
      input: '#22303c',
      ring: '#1da1f2',
      'chart-1': '#1e9df1',
      'chart-2': '#00b87a',
      'chart-3': '#f7b928',
      'chart-4': '#17bf63',
      'chart-5': '#e0245e',
      'background-secondary': '#17181c',
      sidebar: '#17181c',
      'sidebar-foreground': '#d9d9d9',
      'sidebar-primary': '#1da1f2',
      'sidebar-primary-foreground': '#ffffff',
      'sidebar-accent': '#061622',
      'sidebar-accent-foreground': '#1c9cf0',
      'sidebar-border': '#38444d',
      'sidebar-ring': '#1da1f2',
      'shadow-color': 'rgba(29,161,242,0.25)',
    },
  },
};
