export const vintagePaper = {
  label: 'Vintage Paper',
  styles: {
    light: {
      background: '#f5f1e6',
      foreground: '#4a3f35',
      card: '#fffcf5',
      'card-foreground': '#4a3f35',
      popover: '#fffcf5',
      'popover-foreground': '#4a3f35',
      primary: '#a67c52',
      'primary-foreground': '#ffffff',
      secondary: '#e2d8c3',
      'secondary-foreground': '#5c4d3f',
      muted: '#ece5d8',
      'muted-foreground': '#7d6b56',
      accent: '#d4c8aa',
      'accent-foreground': '#4a3f35',
      destructive: '#b54a35',
      'destructive-foreground': '#ffffff',
      border: '#dbd0ba',
      input: '#dbd0ba',
      ring: '#a67c52',
      'chart-1': '#a67c52',
      'chart-2': '#8d6e4c',
      'chart-3': '#735a3a',
      'chart-4': '#b3906f',
      'chart-5': '#c0a080',
      radius: '0.25rem',
      'background-secondary': '#ece5d8',
      sidebar: '#ece5d8',
      'sidebar-foreground': '#4a3f35',
      'sidebar-primary': '#a67c52',
      'sidebar-primary-foreground': '#ffffff',
      'sidebar-accent': '#d4c8aa',
      'sidebar-accent-foreground': '#4a3f35',
      'sidebar-border': '#dbd0ba',
      'sidebar-ring': '#a67c52',
      'font-sans': 'Libre Baskerville, serif',
      'font-serif': 'Lora, serif',
      'font-mono': 'IBM Plex Mono, monospace',
      'shadow-color': 'hsl(28 13% 20%)',
      'shadow-opacity': '0.12',
      'shadow-blur': '5px',
      'shadow-spread': '0px',
      'shadow-offset-x': '2px',
      'shadow-offset-y': '3px',
    },
    dark: {
      background: '#2d2621',
      foreground: '#ece5d8',
      card: '#3a322c',
      'card-foreground': '#ece5d8',
      popover: '#3a322c',
      'popover-foreground': '#ece5d8',
      primary: '#c0a080',
      'primary-foreground': '#2d2621',
      secondary: '#4a4039',
      'secondary-foreground': '#ece5d8',
      muted: '#3a322c',
      'muted-foreground': '#c5bcac',
      accent: '#59493e',
      'accent-foreground': '#ece5d8',
      destructive: '#b54a35',
      'destructive-foreground': '#ffffff',
      border: '#4a4039',
      input: '#4a4039',
      ring: '#c0a080',
      'chart-1': '#c0a080',
      'chart-2': '#b3906f',
      'chart-3': '#a67c52',
      'chart-4': '#8d6e4c',
      'chart-5': '#735a3a',
      radius: '0.25rem',
      'background-secondary': '#2d2621',
      sidebar: '#2d2621',
      'sidebar-foreground': '#ece5d8',
      'sidebar-primary': '#c0a080',
      'sidebar-primary-foreground': '#2d2621',
      'sidebar-accent': '#59493e',
      'sidebar-accent-foreground': '#ece5d8',
      'sidebar-border': '#4a4039',
      'sidebar-ring': '#c0a080',
    },
  },
};
