name: publish-windows

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-tauri-windows:
    permissions:
      contents: write
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install NSIS (Windows)
        run: choco install nsis -y

      - name: install frontend dependencies
        run: pnpm install --frozen-lockfile

      - name: Get version from tauri.conf.json
        id: version
        shell: bash
        run: |
          VERSION=$(node -p "require('./src-tauri/tauri.conf.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build & Draft Release (Windows)
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: .
          tagName: v${{ steps.version.outputs.version }}
          releaseName: 'Ferrix v${{ steps.version.outputs.version }}'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: false
          prerelease: false
          args: ''

      - name: List built files (debug)
        run: |
          echo "==== Bundle tree (Windows) ===="
          ls -R src-tauri/target/release/bundle || true

      - name: Upload artifacts (fallback)
        uses: actions/upload-artifact@v4
        with:
          name: ferrix-windows-${{ github.run_number }}
          path: src-tauri/target/release/bundle/**
